### ISSUE TITLE
Add boundary missing relations

### ISSUE THREAD

**Issue by mihaiJianu** [Torkin1/ISPW_project#105]
If a relation it's missing please Update this ticket too and close it only when all the below tickets are closed.

- [x] << boundary >> User_ContactUser #106 ;

- [x] << boundary >> FindUnemployedUser #107;

- [x] << boundary >> User_validateAFavor  #108 ;

- [x] << boundary >> User_publishAnOfferAd #109;

- [x] << boundary >> User_checkInboxMsgs #110;
- [x] << boundary >> User_ChangeProfileType #111;

- [x]   << boundary >>  User_publishAnRequestAd  #125

**Comment by mihaiJianu** [comment]
Committed on revision 98.
